DROP TABLE IF EXISTS articles_comments CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS article_tags CASCADE;
DROP TABLE IF EXISTS chat CASCADE;
DROP TABLE IF EXISTS tests_results CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50),
                    surname VARCHAR(100),
                    username VARCHAR(20) UNIQUE NOT NULL,
                    password VARCHAR(60) NOT NULL,
                    email VARCHAR(100) UNIQUE NOT NULL,
                    status int NOT NULL,
                    creation_time TIMESTAMP NOT NULL,
                    login_tries int,
                    avatar VARCHAR DEFAULT NULL,
                    bio VARCHAR DEFAULT NULL,
                    linkedIn VARCHAR DEFAULT NULL,
                    twitter VARCHAR DEFAULT NULL,
                    reddit VARCHAR DEFAULT NULL,
                    youtube VARCHAR DEFAULT NULL,
                    comments_upvotes BIGINT ARRAY,
                    articles_upvotes BIGINT ARRAY
                  );

CREATE TABLE sessions(
                    session_id VARCHAR(100) PRIMARY KEY,
                    user_id BIGINT UNIQUE NOT NULL,
                    creation_time TIMESTAMP NOT NULL,
                    FOREIGN KEY (user_id) REFERENCES users (id)
                  );

CREATE TABLE subjects(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(64) NOT NULL,
                    year INT NOT NULL
);

CREATE TABLE questions(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner BIGINT NOT NULL,
                    subject BIGINT NOT NULL,
                    question VARCHAR NOT NULL,
                    choice_test BOOLEAN NOT NULL,
                    shareable BOOLEAN NOT NULL,
                    created TIMESTAMP NOT NULL,
                    last_edited TIMESTAMP,
                    FOREIGN KEY (owner) REFERENCES users(id),
                    FOREIGN KEY (subject) REFERENCES subjects(id)
                    );

CREATE TABLE answers(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    question_id BIGINT NOT NULL,
                    answer VARCHAR NOT NULL,
                    correct BOOLEAN NOT NULL,
                    created TIMESTAMP NOT NULL,
                    last_edited TIMESTAMP,
                    FOREIGN KEY (question_id) REFERENCES questions(id)
                  );

CREATE TABLE tests(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  owner BIGINT NOT NULL,
                  subject BIGINT NOT NULL,
                  questions BIGINT ARRAY,
                  shareable BOOLEAN NOT NULL,
                  created TIMESTAMP DEFAULT now(),
                  last_edited TIMESTAMP DEFAULT now(),
                  downloads INT DEFAULT 0,
                  FOREIGN KEY (owner) REFERENCES users(id),
                  FOREIGN KEY (subject) REFERENCES subjects(id)
);

CREATE TABLE tests_results(
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              test_id BIGINT NOT NULL,
              question_id BIGINT NOT NULL,
              points decimal NOT NULL,
              results_owner BIGINT NOT NULL,
              student_id BIGINT DEFAULT null,
              created TIMESTAMP DEFAULT now(),
              FOREIGN KEY (question_id) REFERENCES questions(id),
              FOREIGN KEY (test_id) REFERENCES tests(id),
              FOREIGN KEY (results_owner) REFERENCES users(id)
);

CREATE TABLE chat(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user1 BIGINT NOT NULL,
            user2 BIGINT NOT NULL,
            sender BIGINT NOT NULL,
            message text NOT NULL,
            sent_on TIMESTAMP DEFAULT now(),
            FOREIGN KEY (user1) REFERENCES users(id),
            FOREIGN KEY (user2) REFERENCES users(id),
            FOREIGN KEY (sender) REFERENCES users(id)
);

CREATE TABLE articles(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner BIGINT NOT NULL,
            contents TEXT NOT NULL,
            upvotes INT DEFAULT 0,
            created_on TIMESTAMP DEFAULT now(),
            tags BIGINT ARRAY DEFAULT null,
            FOREIGN KEY (owner) REFERENCES users(id)
);

CREATE TABLE articles_comments(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            article_id BIGINT NOT NULL,
            commentator BIGINT NOT NULL,
            comment TEXT NOT NULL,
            upvotes INT DEFAULT 0,
            created_on TIMESTAMP DEFAULT now(),
            FOREIGN KEY (article_id) REFERENCES articles(id),
            FOREIGN KEY (commentator) REFERENCES users(id)
);

CREATE TABLE article_tags(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tag TEXT NOT NULL UNIQUE
)